### ISSUE TITLE
Decide on domain name

### ISSUE THREAD

**Issue by garrettwelson** [hratx42-blue-ocean/green-ocean#102]
Options (add additional ones as comments)

- Gruen.money

**Comment by garrettwelson** [comment]
FYI, I use Hover.com for domains and their search for available domains is pretty good. It can suggest similar domains based on whatever word (or words) you enter

**Comment by garrettwelson** [comment]
I'd say ~$40 ($5/person) is the max we should go unless there's something **perfect** that's more, in which case we can discuss

**Comment by dorishui** [comment]
CacheMoney

**Comment by garrettwelson** [comment]
Done! We got cashoverflow.app
