### ISSUE TITLE
[3] Set up express server routes for CRUD access to MongoDB

### ISSUE THREAD

**Issue by kbench09** [hratx42-blue-ocean/green-ocean#89]
- [x] Create new user

- [x] Read user data (set into state at app level)

- [x] Update changes made to user data

- [ ] Delete user (stretch goal?)

For MVP, we're going with a fairly consolidated endpoint plan. 

1. One GET route, which will return all of a user's information, which will then live in state at the app level (or at the stateful page level, whichever is finally decided).

2. One or more POST routes, which will be used to update a user's information. Though we're going to be updated the user's entire document in each go, we might want multiple routes to handle the specifics of the update (create budget category, change budget allotment, add transaction, remove transaction, et al.) It might be best to handle this using middleware (or a convoluted if-else, just for fun) in a single endpoint, however.

3. Delete user is less important for MVP purposes, but would be nice to incorporate if we have time.

**Comment by MitchellDill** [comment]
Update 8/13 midday: We're going to hold the entire user object in state at each page, and hit the POST route with the entire user object. (Technically should probably be a PATCH, but will remain POST for the time being).

**Comment by garrettwelson** [comment]
Marking as closed. Made a separate issue #117 to handle delete functionality as a stretch goal
